accelerator: "gpu"
strategy: "auto"
devices:
  - 0
check_val_every_n_epoch: 1
deterministic: true
max_epochs: 720
min_epochs: 10
enable_progress_bar: true
default_root_dir: ./logs
precision: bf16-true
