# generated by datamodel-codegen:
#   filename:  config.json
#   timestamp: 2024-12-17T11:54:19+00:00

from __future__ import annotations

from typing import List

from pydantic import BaseModel


class Pretrained(BaseModel):
    model: str


class Trainer(BaseModel):
    accelerator: str
    strategy: str
    devices: str
    check_val_every_n_epoch: int
    deterministic: bool
    max_epochs: int
    min_epochs: int
    enable_progress_bar: bool
    default_root_dir: str


class Paths(BaseModel):
    root_dir: str
    data_dir: str
    log_dir: str
    output_dir: str
    work_dir: str


class Extras(BaseModel):
    ignore_warnings: bool
    enforce_tags: bool
    print_config: bool


class FinetuneConfig(BaseModel):
    task_name: str
    tags: List[str]
    train: bool
    test: bool
    ckpt_path: None
    seed: None
    pretrained: Pretrained
    trainer: Trainer
    paths: Paths
    extras: Extras
